import Foundation

struct DataProvider: Sendable {

    static let shared = DataProvider()
    private init() {}

    var allQuestions: [Question] {
        [
            // MARK: Ice Breakers (50)
            Question(text: "What's a skill you're secretly proud of?", category: .iceBreakers, depth: .light),
            Question(text: "If your life had a theme song, what would it be?", category: .iceBreakers, depth: .light),
            Question(text: "What's the most unusual thing in your home right now?", category: .iceBreakers, depth: .light),
            Question(text: "What's your go-to comfort food after a bad day?", category: .iceBreakers, depth: .light),
            Question(text: "If you could only eat one cuisine forever, what would it be?", category: .iceBreakers, depth: .light),
            Question(text: "What's the last thing that made you laugh out loud?", category: .iceBreakers, depth: .light),
            Question(text: "Are you more of a morning person or a night owl?", category: .iceBreakers, depth: .light),
            Question(text: "What's a show you've rewatched more than three times?", category: .iceBreakers, depth: .light),
            Question(text: "If you had to describe yourself in three words, what would they be?", category: .iceBreakers, depth: .medium),
            Question(text: "What's something you're better at than most people realise?", category: .iceBreakers, depth: .medium),
            Question(text: "What's the best gift you've ever received?", category: .iceBreakers, depth: .light),
            Question(text: "Do you have any hidden talents?", category: .iceBreakers, depth: .light),
            Question(text: "What's a hobby you've always wanted to try?", category: .iceBreakers, depth: .light),
            Question(text: "Coffee, tea, or something else entirely?", category: .iceBreakers, depth: .light),
            Question(text: "What's the last book you genuinely couldn't put down?", category: .iceBreakers, depth: .light),
            Question(text: "Are you a planner or do you prefer to go with the flow?", category: .iceBreakers, depth: .light),
            Question(text: "What's your most-used app on your phone?", category: .iceBreakers, depth: .light),
            Question(text: "What's a movie that genuinely surprised you?", category: .iceBreakers, depth: .light),
            Question(text: "Do you prefer cities, countryside, or the coast?", category: .iceBreakers, depth: .light),
            Question(text: "What's something on your bucket list you haven't told many people?", category: .iceBreakers, depth: .medium),
            Question(text: "What's the best piece of advice you ever ignored?", category: .iceBreakers, depth: .medium),
            Question(text: "What's your signature dish to cook for others?", category: .iceBreakers, depth: .light),
            Question(text: "If you could master any instrument overnight, which would you choose?", category: .iceBreakers, depth: .light),
            Question(text: "What's the most spontaneous thing you've ever done?", category: .iceBreakers, depth: .light),
            Question(text: "What's a word you overuse?", category: .iceBreakers, depth: .light),
            Question(text: "Mountains in winter or beach in summer?", category: .iceBreakers, depth: .light),
            Question(text: "What's the earliest memory you can recall?", category: .iceBreakers, depth: .medium),
            Question(text: "What's something that always puts you in a good mood?", category: .iceBreakers, depth: .light),
            Question(text: "Do you prefer to text or call?", category: .iceBreakers, depth: .light),
            Question(text: "What's a place in your city you think is underrated?", category: .iceBreakers, depth: .light),
            Question(text: "What's your guilty pleasure TV show?", category: .iceBreakers, depth: .light),
            Question(text: "If you could only listen to one album forever, what would it be?", category: .iceBreakers, depth: .light),
            Question(text: "What's a compliment you remember receiving years later?", category: .iceBreakers, depth: .medium),
            Question(text: "Are you more of an introvert or extrovert at heart?", category: .iceBreakers, depth: .medium),
            Question(text: "What's the most interesting thing about where you grew up?", category: .iceBreakers, depth: .light),
            Question(text: "What's something you collect, even informally?", category: .iceBreakers, depth: .light),
            Question(text: "What's the weirdest job you've ever had or considered?", category: .iceBreakers, depth: .light),
            Question(text: "Early bird or night owl — and are you happy with that?", category: .iceBreakers, depth: .light),
            Question(text: "What's something you do to unwind that others might find odd?", category: .iceBreakers, depth: .medium),
            Question(text: "What's your favourite season and why does it win?", category: .iceBreakers, depth: .light),
            Question(text: "What's a smell that instantly takes you somewhere?", category: .iceBreakers, depth: .light),
            Question(text: "If you could have one superpower for a day, what would you pick?", category: .iceBreakers, depth: .light),
            Question(text: "What's the most ridiculous thing you believed as a child?", category: .iceBreakers, depth: .light),
            Question(text: "What's a skill you think everyone should learn?", category: .iceBreakers, depth: .medium),
            Question(text: "What's something you always have in your bag or pockets?", category: .iceBreakers, depth: .light),
            Question(text: "What would your friends say is your most defining trait?", category: .iceBreakers, depth: .medium),
            Question(text: "What's a food you hated as a kid but love now?", category: .iceBreakers, depth: .light),
            Question(text: "If your home had a theme, what would it be?", category: .iceBreakers, depth: .light),
            Question(text: "What's the most interesting tab open in your browser right now?", category: .iceBreakers, depth: .light),
            Question(text: "What's something you're looking forward to this month?", category: .iceBreakers, depth: .light),

            // MARK: Dreams & Goals (50)
            Question(text: "What's one thing you want to accomplish in the next five years?", category: .dreams, depth: .medium),
            Question(text: "If money were no object, how would you spend your days?", category: .dreams, depth: .medium),
            Question(text: "What's a dream you've held onto since childhood?", category: .dreams, depth: .medium),
            Question(text: "Is there a version of yourself you're actively working toward?", category: .dreams, depth: .deep),
            Question(text: "What legacy do you hope to leave behind?", category: .dreams, depth: .deep),
            Question(text: "What would you do if you knew you couldn't fail?", category: .dreams, depth: .medium),
            Question(text: "What does your ideal Saturday look like ten years from now?", category: .dreams, depth: .medium),
            Question(text: "Is there a place in the world you feel called to live someday?", category: .dreams, depth: .light),
            Question(text: "What's a goal you've been putting off that you know you should start?", category: .dreams, depth: .deep),
            Question(text: "Who inspires you the most and why?", category: .dreams, depth: .medium),
            Question(text: "What does success look like to you — honestly?", category: .dreams, depth: .deep),
            Question(text: "What's something you want to learn in the next year?", category: .dreams, depth: .light),
            Question(text: "If you could change careers tomorrow, what would you do?", category: .dreams, depth: .medium),
            Question(text: "What's the one project you wish you had more time to pursue?", category: .dreams, depth: .medium),
            Question(text: "What kind of person do you want to be in ten years?", category: .dreams, depth: .deep),
            Question(text: "What would you build if you had unlimited resources?", category: .dreams, depth: .medium),
            Question(text: "What's a creative pursuit you've always wanted to explore?", category: .dreams, depth: .light),
            Question(text: "Is there something you've always wanted to write or create?", category: .dreams, depth: .medium),
            Question(text: "What's a risk you want to take but haven't yet?", category: .dreams, depth: .deep),
            Question(text: "What does your dream home look like?", category: .dreams, depth: .light),
            Question(text: "If you could make one change to the world, what would it be?", category: .dreams, depth: .deep),
            Question(text: "What's a cause you'd dedicate more time to if you could?", category: .dreams, depth: .medium),
            Question(text: "What does freedom mean to you in a practical sense?", category: .dreams, depth: .deep),
            Question(text: "What's something you'd attempt if you had no fear of judgement?", category: .dreams, depth: .deep),
            Question(text: "If you wrote a book, what would it be about?", category: .dreams, depth: .medium),
            Question(text: "What's the most meaningful way you can imagine spending a year?", category: .dreams, depth: .deep),
            Question(text: "What relationship in your life do you most want to deepen?", category: .dreams, depth: .deep),
            Question(text: "What does retirement look like in your ideal world?", category: .dreams, depth: .medium),
            Question(text: "Is there a language you've always wanted to speak fluently?", category: .dreams, depth: .light),
            Question(text: "What's a version of your life you chose not to pursue — and do you wonder about it?", category: .dreams, depth: .deep),
            Question(text: "What would you do with a month of complete freedom?", category: .dreams, depth: .medium),
            Question(text: "What's a skill you admire in others and want for yourself?", category: .dreams, depth: .medium),
            Question(text: "What's the most important thing you want to teach a future generation?", category: .dreams, depth: .deep),
            Question(text: "What does a truly fulfilling week look like to you?", category: .dreams, depth: .medium),
            Question(text: "What's something you want to be remembered for?", category: .dreams, depth: .deep),
            Question(text: "If you could go back to school for anything, what would it be?", category: .dreams, depth: .medium),
            Question(text: "What's a dream that feels just out of reach right now?", category: .dreams, depth: .deep),
            Question(text: "Where do you want to be living in five years?", category: .dreams, depth: .medium),
            Question(text: "What's a habit you're trying to build?", category: .dreams, depth: .light),
            Question(text: "What does your ideal morning routine look like?", category: .dreams, depth: .light),
            Question(text: "What's one thing you want to have figured out by the end of this year?", category: .dreams, depth: .medium),
            Question(text: "What would you do if you had six months and no obligations?", category: .dreams, depth: .medium),
            Question(text: "What's a contribution you want to make to your community?", category: .dreams, depth: .deep),
            Question(text: "Is there someone you want to reconnect with?", category: .dreams, depth: .medium),
            Question(text: "What does your most courageous self look like?", category: .dreams, depth: .deep),
            Question(text: "What's a personal standard you want to raise?", category: .dreams, depth: .deep),
            Question(text: "What kind of work makes you lose track of time?", category: .dreams, depth: .medium),
            Question(text: "What's the most exciting thing on your horizon right now?", category: .dreams, depth: .light),
            Question(text: "If you could mentor someone, what would you want to pass on?", category: .dreams, depth: .deep),
            Question(text: "What's one thing you're actively choosing to prioritise this year?", category: .dreams, depth: .medium),

            // MARK: Childhood (50)
            Question(text: "What's your favourite memory from childhood?", category: .childhood, depth: .light),
            Question(text: "What did you want to be when you grew up?", category: .childhood, depth: .light),
            Question(text: "Did you have a best friend growing up? What were they like?", category: .childhood, depth: .medium),
            Question(text: "What's a tradition from your family you still carry with you?", category: .childhood, depth: .medium),
            Question(text: "What's the most trouble you ever got into as a kid?", category: .childhood, depth: .light),
            Question(text: "What book or movie defined your childhood?", category: .childhood, depth: .light),
            Question(text: "Was there a moment growing up that shaped who you are today?", category: .childhood, depth: .deep),
            Question(text: "What's something your parents taught you that you're grateful for?", category: .childhood, depth: .medium),
            Question(text: "Did you have any weird childhood fears?", category: .childhood, depth: .light),
            Question(text: "What's a toy or game from your childhood most people wouldn't remember?", category: .childhood, depth: .light),
            Question(text: "What did your bedroom look like as a kid?", category: .childhood, depth: .light),
            Question(text: "What's the most adventurous thing you did as a child?", category: .childhood, depth: .light),
            Question(text: "Did you have a favourite hiding spot growing up?", category: .childhood, depth: .light),
            Question(text: "What's a family holiday memory you return to often?", category: .childhood, depth: .medium),
            Question(text: "What subject did you love at school that surprised people?", category: .childhood, depth: .light),
            Question(text: "Who was your childhood hero and why?", category: .childhood, depth: .medium),
            Question(text: "What's something you wish you'd been taught earlier in life?", category: .childhood, depth: .deep),
            Question(text: "Did you have a childhood pet that meant a lot to you?", category: .childhood, depth: .light),
            Question(text: "What song takes you straight back to being young?", category: .childhood, depth: .light),
            Question(text: "Were you more of a rule-follower or a rule-bender growing up?", category: .childhood, depth: .medium),
            Question(text: "What's something you did as a kid you hope to pass on?", category: .childhood, depth: .medium),
            Question(text: "What was the first thing you ever saved up to buy yourself?", category: .childhood, depth: .light),
            Question(text: "Who in your childhood had the most influence on you?", category: .childhood, depth: .deep),
            Question(text: "What's a childhood friendship that still means something to you?", category: .childhood, depth: .medium),
            Question(text: "What was your favourite thing to do on a summer day as a kid?", category: .childhood, depth: .light),
            Question(text: "Did you have a childhood nickname? How did you feel about it?", category: .childhood, depth: .light),
            Question(text: "What's the biggest lie you told as a child?", category: .childhood, depth: .light),
            Question(text: "Were you close with your grandparents?", category: .childhood, depth: .medium),
            Question(text: "What's a meal from childhood you still crave?", category: .childhood, depth: .light),
            Question(text: "What did weekends look like in your house growing up?", category: .childhood, depth: .medium),
            Question(text: "What did your family do together that you loved?", category: .childhood, depth: .medium),
            Question(text: "What's a childhood dream that came true in some form?", category: .childhood, depth: .medium),
            Question(text: "Was there something you were passionate about as a kid that you've let go of?", category: .childhood, depth: .deep),
            Question(text: "What's the best birthday you can remember?", category: .childhood, depth: .light),
            Question(text: "Did you have a favourite teacher? What made them stand out?", category: .childhood, depth: .medium),
            Question(text: "What did you believe about the world as a child that turned out to be wrong?", category: .childhood, depth: .deep),
            Question(text: "What's something a parent or guardian said that has stuck with you?", category: .childhood, depth: .deep),
            Question(text: "Where did you grow up, and what do you miss about it?", category: .childhood, depth: .medium),
            Question(text: "What was your first experience of something being unfair?", category: .childhood, depth: .deep),
            Question(text: "What's a game you played as a kid that you'd love to play now?", category: .childhood, depth: .light),
            Question(text: "Were you shy or outgoing as a child — and has that changed?", category: .childhood, depth: .medium),
            Question(text: "What's the most valuable thing you owned as a kid?", category: .childhood, depth: .light),
            Question(text: "Did you have a sport or activity that defined a big part of your youth?", category: .childhood, depth: .medium),
            Question(text: "What's a smell from childhood that brings everything back?", category: .childhood, depth: .light),
            Question(text: "What was the first movie you saw in a cinema?", category: .childhood, depth: .light),
            Question(text: "What's a hard moment from growing up that made you stronger?", category: .childhood, depth: .deep),
            Question(text: "What's something your younger self would be proud of you for?", category: .childhood, depth: .deep),
            Question(text: "Did you have a childhood ritual that felt important to you?", category: .childhood, depth: .medium),
            Question(text: "What's the funniest misunderstanding you had as a child?", category: .childhood, depth: .light),
            Question(text: "If you could go back to one day from your childhood, which would it be?", category: .childhood, depth: .deep),

            // MARK: Deep Thoughts (50)
            Question(text: "What's something you believe that most people disagree with?", category: .deepThoughts, depth: .deep),
            Question(text: "How do you define happiness?", category: .deepThoughts, depth: .deep),
            Question(text: "What's a moment that fundamentally changed your worldview?", category: .deepThoughts, depth: .deep),
            Question(text: "Do you think people can truly change?", category: .deepThoughts, depth: .deep),
            Question(text: "What does love mean to you?", category: .deepThoughts, depth: .deep),
            Question(text: "If you could have one conversation with your future self, what would you ask?", category: .deepThoughts, depth: .deep),
            Question(text: "What's the hardest lesson life has taught you?", category: .deepThoughts, depth: .deep),
            Question(text: "Do you think we create our own meaning, or is something larger at work?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something you've changed your mind about in the last year?", category: .deepThoughts, depth: .medium),
            Question(text: "If you could relive one day of your life, which would it be and why?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something you know to be true but can't fully explain?", category: .deepThoughts, depth: .deep),
            Question(text: "What do you think is the most underrated virtue?", category: .deepThoughts, depth: .deep),
            Question(text: "Is there something you've never forgiven yourself for?", category: .deepThoughts, depth: .deep),
            Question(text: "What's the most important question you're sitting with right now?", category: .deepThoughts, depth: .deep),
            Question(text: "What does integrity look like to you in daily life?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something most people take for granted?", category: .deepThoughts, depth: .medium),
            Question(text: "Do you think loneliness is more about circumstance or mindset?", category: .deepThoughts, depth: .deep),
            Question(text: "What's the difference between being alone and being lonely to you?", category: .deepThoughts, depth: .deep),
            Question(text: "What does it mean to live a good life?", category: .deepThoughts, depth: .deep),
            Question(text: "What's a belief you hold that you've never been fully challenged on?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something society celebrates that you find hollow?", category: .deepThoughts, depth: .deep),
            Question(text: "When have you felt most like yourself?", category: .deepThoughts, depth: .deep),
            Question(text: "What do you owe other people, if anything?", category: .deepThoughts, depth: .deep),
            Question(text: "Is there a version of your life you grieve not having lived?", category: .deepThoughts, depth: .deep),
            Question(text: "What would you do differently if you knew no one would judge you?", category: .deepThoughts, depth: .deep),
            Question(text: "What does trust mean to you — and how do you know when you have it?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something that used to scare you that no longer does?", category: .deepThoughts, depth: .medium),
            Question(text: "What's the most compassionate thing you've ever witnessed?", category: .deepThoughts, depth: .deep),
            Question(text: "Do you believe in second chances? Where's the limit?", category: .deepThoughts, depth: .deep),
            Question(text: "What's a contradiction you live with that you've made peace with?", category: .deepThoughts, depth: .deep),
            Question(text: "What does courage look like in ordinary, everyday life?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something you've had to unlearn?", category: .deepThoughts, depth: .deep),
            Question(text: "Is it possible to truly know another person?", category: .deepThoughts, depth: .deep),
            Question(text: "What's the most significant choice you've ever made?", category: .deepThoughts, depth: .deep),
            Question(text: "What do you think happens when we die?", category: .deepThoughts, depth: .deep),
            Question(text: "What's a value you won't compromise on, no matter what?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something you're still figuring out about yourself?", category: .deepThoughts, depth: .medium),
            Question(text: "What's your relationship with failure?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something you've accepted that took years to come to terms with?", category: .deepThoughts, depth: .deep),
            Question(text: "Do you think kindness is natural or learned?", category: .deepThoughts, depth: .deep),
            Question(text: "What's an experience that made you feel genuinely humbled?", category: .deepThoughts, depth: .deep),
            Question(text: "What would you want written on your gravestone?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something you wish you'd said to someone while you had the chance?", category: .deepThoughts, depth: .deep),
            Question(text: "What does home mean to you beyond the physical place?", category: .deepThoughts, depth: .deep),
            Question(text: "What's the most important thing you've learned from a difficult relationship?", category: .deepThoughts, depth: .deep),
            Question(text: "What's a question you're afraid to find the answer to?", category: .deepThoughts, depth: .deep),
            Question(text: "What do you think is the root of most human suffering?", category: .deepThoughts, depth: .deep),
            Question(text: "What's the kindest lie you've ever told?", category: .deepThoughts, depth: .deep),
            Question(text: "What's something you've only recently come to appreciate?", category: .deepThoughts, depth: .medium),
            Question(text: "What's the hardest thing about being you right now?", category: .deepThoughts, depth: .deep),

            // MARK: Fun & Silly (50)
            Question(text: "What's the weirdest food combination you secretly enjoy?", category: .funAndSilly, depth: .light),
            Question(text: "If you were a cartoon character, who would you be?", category: .funAndSilly, depth: .light),
            Question(text: "What's your most embarrassing moment you can laugh about now?", category: .funAndSilly, depth: .light),
            Question(text: "If you had to survive a zombie apocalypse, what's your strategy?", category: .funAndSilly, depth: .light),
            Question(text: "Would you rather be able to fly or be invisible?", category: .funAndSilly, depth: .light),
            Question(text: "What's a conspiracy theory you find strangely compelling?", category: .funAndSilly, depth: .light),
            Question(text: "If you opened a restaurant, what would it be called?", category: .funAndSilly, depth: .light),
            Question(text: "What's the strangest dream you can remember?", category: .funAndSilly, depth: .light),
            Question(text: "If animals could talk, which would be the most annoying?", category: .funAndSilly, depth: .light),
            Question(text: "What's your karaoke go-to song?", category: .funAndSilly, depth: .light),
            Question(text: "What's the most useless talent you have?", category: .funAndSilly, depth: .light),
            Question(text: "If you were a villain, what would your evil plan be?", category: .funAndSilly, depth: .light),
            Question(text: "What would your reality TV show be called?", category: .funAndSilly, depth: .light),
            Question(text: "If you could swap lives with a fictional character for a week, who?", category: .funAndSilly, depth: .light),
            Question(text: "What's the weirdest thing you've googled recently?", category: .funAndSilly, depth: .light),
            Question(text: "If you had to wear one outfit every day for a year, what would it be?", category: .funAndSilly, depth: .light),
            Question(text: "What's the worst haircut you've ever had?", category: .funAndSilly, depth: .light),
            Question(text: "If you could uninvent one thing, what would it be?", category: .funAndSilly, depth: .light),
            Question(text: "What's a completely irrational thing that irritates you?", category: .funAndSilly, depth: .light),
            Question(text: "Would you rather fight one horse-sized duck or a hundred duck-sized horses?", category: .funAndSilly, depth: .light),
            Question(text: "What's the most dramatic thing you've done over something minor?", category: .funAndSilly, depth: .light),
            Question(text: "If your pet could talk, what's the first thing they'd say?", category: .funAndSilly, depth: .light),
            Question(text: "What's the silliest thing you've spent money on and never regretted?", category: .funAndSilly, depth: .light),
            Question(text: "What fictional world would you least want to live in?", category: .funAndSilly, depth: .light),
            Question(text: "If you could add one rule to society that everyone had to follow, what would it be?", category: .funAndSilly, depth: .light),
            Question(text: "What's the most creative excuse you've ever used?", category: .funAndSilly, depth: .light),
            Question(text: "What's a completely unexplainable habit you have?", category: .funAndSilly, depth: .light),
            Question(text: "If you could compete in any Olympic event, which would you choose?", category: .funAndSilly, depth: .light),
            Question(text: "What's your go-to dance move when no one's watching?", category: .funAndSilly, depth: .light),
            Question(text: "If you were a ghost, where would you haunt?", category: .funAndSilly, depth: .light),
            Question(text: "What's the most ridiculous argument you've gotten into?", category: .funAndSilly, depth: .light),
            Question(text: "What would your warning label say if you were a product?", category: .funAndSilly, depth: .light),
            Question(text: "If you could only communicate in movie quotes for a day, which movie would you use?", category: .funAndSilly, depth: .light),
            Question(text: "What's a word you find inherently funny?", category: .funAndSilly, depth: .light),
            Question(text: "If your life were a genre of film, what genre is it right now?", category: .funAndSilly, depth: .light),
            Question(text: "What's something you're weirdly competitive about?", category: .funAndSilly, depth: .light),
            Question(text: "What's your most controversial food opinion?", category: .funAndSilly, depth: .light),
            Question(text: "If you could have any animal as a pet with no consequences, what would you choose?", category: .funAndSilly, depth: .light),
            Question(text: "What's the most absurd hill you'd die on?", category: .funAndSilly, depth: .light),
            Question(text: "If you could only eat one thing at every party for the rest of your life, what is it?", category: .funAndSilly, depth: .light),
            Question(text: "What's a childhood cartoon you'd genuinely watch today?", category: .funAndSilly, depth: .light),
            Question(text: "If you had a theme song that played when you walked into a room, what would it be?", category: .funAndSilly, depth: .light),
            Question(text: "What's the worst advice you've ever been given — and followed?", category: .funAndSilly, depth: .light),
            Question(text: "What's the most extra thing you've ever done?", category: .funAndSilly, depth: .light),
            Question(text: "If you were a type of weather, what would you be?", category: .funAndSilly, depth: .light),
            Question(text: "What's a skill you have that would be completely useless in a survival situation?", category: .funAndSilly, depth: .light),
            Question(text: "If you could time-travel but only to observe, never interact, where would you go?", category: .funAndSilly, depth: .light),
            Question(text: "What would your autobiography's opening line be?", category: .funAndSilly, depth: .light),
            Question(text: "What's the most over-the-top thing you'd do if you won the lottery?", category: .funAndSilly, depth: .light),
            Question(text: "If you were a kitchen appliance, which would you be and why?", category: .funAndSilly, depth: .light),

            // MARK: Travel (50)
            Question(text: "What's the most beautiful place you've ever been?", category: .travel, depth: .light),
            Question(text: "Do you prefer planned trips or spontaneous adventures?", category: .travel, depth: .light),
            Question(text: "What's a place on your bucket list and why?", category: .travel, depth: .medium),
            Question(text: "What's the best meal you've ever had while travelling?", category: .travel, depth: .light),
            Question(text: "Have you ever had a travel experience that changed you?", category: .travel, depth: .deep),
            Question(text: "Beach, mountains, or city — where do you feel most at home?", category: .travel, depth: .light),
            Question(text: "What's the worst travel story that became a great story?", category: .travel, depth: .medium),
            Question(text: "If you could live anywhere for a year, where and why?", category: .travel, depth: .medium),
            Question(text: "What culture or country fascinates you most?", category: .travel, depth: .medium),
            Question(text: "Would you ever pack up and move to a new country?", category: .travel, depth: .medium),
            Question(text: "What's the most remote place you've ever been?", category: .travel, depth: .light),
            Question(text: "Do you prefer travelling alone or with others?", category: .travel, depth: .medium),
            Question(text: "What's a city you've visited that surprised you completely?", category: .travel, depth: .light),
            Question(text: "What's your worst travel nightmare that actually happened?", category: .travel, depth: .light),
            Question(text: "Is there a country you'd go back to again and again?", category: .travel, depth: .light),
            Question(text: "What's the most interesting person you've ever met while travelling?", category: .travel, depth: .medium),
            Question(text: "What do you always pack that most people wouldn't think to bring?", category: .travel, depth: .light),
            Question(text: "What's the longest you've ever been away from home?", category: .travel, depth: .light),
            Question(text: "Have you ever got completely lost somewhere? What happened?", category: .travel, depth: .light),
            Question(text: "What's a local experience you've had that no tourist guide would recommend?", category: .travel, depth: .medium),
            Question(text: "What's your travel philosophy — slow and deep or fast and wide?", category: .travel, depth: .medium),
            Question(text: "What's the most overrated tourist destination you've visited?", category: .travel, depth: .light),
            Question(text: "What travel experience are you most proud of?", category: .travel, depth: .medium),
            Question(text: "Is there a place you've been that felt like it could have been home?", category: .travel, depth: .deep),
            Question(text: "What's the most beautiful natural thing you've witnessed while travelling?", category: .travel, depth: .light),
            Question(text: "What's a travel mistake you only made once?", category: .travel, depth: .light),
            Question(text: "What's the most culturally different place you've experienced?", category: .travel, depth: .medium),
            Question(text: "Have you ever stayed with locals rather than in a hotel? What was it like?", category: .travel, depth: .medium),
            Question(text: "What's a journey — not a destination — that was memorable?", category: .travel, depth: .medium),
            Question(text: "What country's food do you think is the most underrated?", category: .travel, depth: .light),
            Question(text: "Is there somewhere you were afraid to go but loved when you got there?", category: .travel, depth: .medium),
            Question(text: "What's the most unexpectedly moving thing you've experienced abroad?", category: .travel, depth: .deep),
            Question(text: "Do you think travel makes you a better person — and has it?", category: .travel, depth: .deep),
            Question(text: "What's a language barrier story you'll never forget?", category: .travel, depth: .light),
            Question(text: "Where would you go if you needed to completely reset?", category: .travel, depth: .medium),
            Question(text: "What's the first trip you took that felt truly independent?", category: .travel, depth: .medium),
            Question(text: "Is there a place you've been that you've never told many people about?", category: .travel, depth: .medium),
            Question(text: "What's a mode of transport you've used that you'd never choose again?", category: .travel, depth: .light),
            Question(text: "What's something travel has taught you about yourself?", category: .travel, depth: .deep),
            Question(text: "If you could only visit one continent for the rest of your life, which would it be?", category: .travel, depth: .light),
            Question(text: "What's the most luxurious travel experience you've had?", category: .travel, depth: .light),
            Question(text: "What's the most stripped-back, basic travel experience you've loved?", category: .travel, depth: .light),
            Question(text: "Have you ever missed a flight or connection? What did you do?", category: .travel, depth: .light),
            Question(text: "What's a travel ritual you always follow?", category: .travel, depth: .light),
            Question(text: "What's a festival or event somewhere in the world you'd love to attend?", category: .travel, depth: .light),
            Question(text: "What's the most surreal landscape you've ever stood in?", category: .travel, depth: .medium),
            Question(text: "Is there somewhere you've been that changed how you see home?", category: .travel, depth: .deep),
            Question(text: "What's a country you've never been to that you think about often?", category: .travel, depth: .light),
            Question(text: "What's the smallest, most obscure place that left the biggest impression on you?", category: .travel, depth: .medium),
            Question(text: "If you could take one person anywhere in the world right now, where would you go?", category: .travel, depth: .medium),

            // MARK: Love & Life (50)
            Question(text: "What does a healthy relationship look like to you?", category: .loveAndLife, depth: .deep),
            Question(text: "What's something small that makes your day significantly better?", category: .loveAndLife, depth: .light),
            Question(text: "How do you show someone you care about them?", category: .loveAndLife, depth: .medium),
            Question(text: "What's a dealbreaker for you in a relationship?", category: .loveAndLife, depth: .medium),
            Question(text: "What's your love language?", category: .loveAndLife, depth: .medium),
            Question(text: "What do you need most when you're going through something hard?", category: .loveAndLife, depth: .deep),
            Question(text: "What's the kindest thing someone has ever done for you?", category: .loveAndLife, depth: .medium),
            Question(text: "What's one thing you wish people understood about you?", category: .loveAndLife, depth: .deep),
            Question(text: "What does a perfect evening look like to you?", category: .loveAndLife, depth: .light),
            Question(text: "Are you someone who falls slowly or all at once?", category: .loveAndLife, depth: .deep),
            Question(text: "What's something you've never compromised on in a relationship?", category: .loveAndLife, depth: .deep),
            Question(text: "What's the most important thing you've learned from a past relationship?", category: .loveAndLife, depth: .deep),
            Question(text: "How do you know when you can trust someone?", category: .loveAndLife, depth: .deep),
            Question(text: "What does commitment mean to you?", category: .loveAndLife, depth: .deep),
            Question(text: "What's something you need in a friendship that you rarely ask for?", category: .loveAndLife, depth: .deep),
            Question(text: "What's the most loving thing someone has said to you?", category: .loveAndLife, depth: .medium),
            Question(text: "How do you handle conflict with someone you love?", category: .loveAndLife, depth: .deep),
            Question(text: "What makes you feel most seen by another person?", category: .loveAndLife, depth: .deep),
            Question(text: "What's something you find unexpectedly attractive in people?", category: .loveAndLife, depth: .medium),
            Question(text: "What does vulnerability mean to you?", category: .loveAndLife, depth: .deep),
            Question(text: "Is there something you find hard to ask for, even from people close to you?", category: .loveAndLife, depth: .deep),
            Question(text: "What's the most important quality in a life partner?", category: .loveAndLife, depth: .deep),
            Question(text: "How has your idea of love changed as you've gotten older?", category: .loveAndLife, depth: .deep),
            Question(text: "What's something you do for yourself that also shows you love yourself?", category: .loveAndLife, depth: .medium),
            Question(text: "What's a relationship in your life you've had to grieve?", category: .loveAndLife, depth: .deep),
            Question(text: "How do you know when a friendship is truly deep?", category: .loveAndLife, depth: .medium),
            Question(text: "What's something you've forgiven someone for that surprised you?", category: .loveAndLife, depth: .deep),
            Question(text: "Do you think people can love more than one person at a time?", category: .loveAndLife, depth: .deep),
            Question(text: "What's a way you've grown because of someone else?", category: .loveAndLife, depth: .deep),
            Question(text: "What does it feel like for you when you're truly happy?", category: .loveAndLife, depth: .medium),
            Question(text: "What's a small daily ritual that matters to you?", category: .loveAndLife, depth: .light),
            Question(text: "What's something that makes you feel immediately at ease with someone?", category: .loveAndLife, depth: .medium),
            Question(text: "What's the longest friendship you've maintained and what keeps it alive?", category: .loveAndLife, depth: .medium),
            Question(text: "What does loyalty mean to you in practice?", category: .loveAndLife, depth: .deep),
            Question(text: "Is there something you've always wanted to say to someone but haven't?", category: .loveAndLife, depth: .deep),
            Question(text: "What's a small act of love you think is deeply underrated?", category: .loveAndLife, depth: .medium),
            Question(text: "What does loneliness feel like for you, and what's your relationship with it?", category: .loveAndLife, depth: .deep),
            Question(text: "What's something you've stopped apologising for?", category: .loveAndLife, depth: .deep),
            Question(text: "How do you recognise when someone is truly good for you?", category: .loveAndLife, depth: .deep),
            Question(text: "What's something you're still learning about how to be a good partner or friend?", category: .loveAndLife, depth: .deep),
            Question(text: "What's the best relationship advice you've ever received?", category: .loveAndLife, depth: .medium),
            Question(text: "What makes you laugh with someone rather than at them?", category: .loveAndLife, depth: .medium),
            Question(text: "Do you think you love differently than most people — and how?", category: .loveAndLife, depth: .deep),
            Question(text: "What's something about yourself you hope a partner will always accept?", category: .loveAndLife, depth: .deep),
            Question(text: "What do you think is the secret to a lasting relationship?", category: .loveAndLife, depth: .deep),
            Question(text: "What's a moment where someone showed up for you in a way you'll never forget?", category: .loveAndLife, depth: .deep),
            Question(text: "What's the most honest thing you've ever said to someone you love?", category: .loveAndLife, depth: .deep),
            Question(text: "What does being loved well feel like to you?", category: .loveAndLife, depth: .deep),
            Question(text: "What's something you've done for love that you'd do again in a heartbeat?", category: .loveAndLife, depth: .deep),
            Question(text: "What's a boundary you've set that changed a relationship for the better?", category: .loveAndLife, depth: .deep),

            // MARK: Hypothetical (50)
            Question(text: "If you could have dinner with anyone, living or dead, who would it be?", category: .hypothetical, depth: .light),
            Question(text: "If you woke up as the opposite gender for a day, what's the first thing you'd do?", category: .hypothetical, depth: .light),
            Question(text: "If you could erase one memory, would you?", category: .hypothetical, depth: .deep),
            Question(text: "If you had 24 hours left on Earth, how would you spend it?", category: .hypothetical, depth: .deep),
            Question(text: "Would you rather know when you're going to die, or how?", category: .hypothetical, depth: .deep),
            Question(text: "If you could change one thing about how you were raised, what would it be?", category: .hypothetical, depth: .deep),
            Question(text: "If you could master any skill instantly, what would you choose?", category: .hypothetical, depth: .light),
            Question(text: "If you could swap lives with someone for a week, who would it be?", category: .hypothetical, depth: .medium),
            Question(text: "Would you choose to live forever if you could?", category: .hypothetical, depth: .deep),
            Question(text: "If a movie was made about your life, what genre would it be?", category: .hypothetical, depth: .light),
            Question(text: "If you could wake up tomorrow with one new skill, what would it be?", category: .hypothetical, depth: .light),
            Question(text: "Would you rather be the most talented person in the room or the most liked?", category: .hypothetical, depth: .medium),
            Question(text: "If you could undo one decision, what would it be?", category: .hypothetical, depth: .deep),
            Question(text: "If you had to give up one of your senses, which would you choose?", category: .hypothetical, depth: .medium),
            Question(text: "If you could guarantee one thing about the future, what would it be?", category: .hypothetical, depth: .deep),
            Question(text: "Would you rather know all the answers or always ask the right questions?", category: .hypothetical, depth: .deep),
            Question(text: "If you could go back to any point in history as an observer, where would you go?", category: .hypothetical, depth: .medium),
            Question(text: "If someone gave you a year off with full pay, what would you actually do?", category: .hypothetical, depth: .medium),
            Question(text: "If you could live inside any book for a month, which would you choose?", category: .hypothetical, depth: .light),
            Question(text: "Would you take a pill that removed all fear from your life?", category: .hypothetical, depth: .deep),
            Question(text: "If you could have one conversation you never got to have, who would it be with?", category: .hypothetical, depth: .deep),
            Question(text: "If you could only keep three possessions, what would they be?", category: .hypothetical, depth: .medium),
            Question(text: "Would you rather be wildly famous for something you hate or unknown for something you love?", category: .hypothetical, depth: .deep),
            Question(text: "If you could change one thing about how the world works, what would it be?", category: .hypothetical, depth: .deep),
            Question(text: "If you discovered you had one year to live, what would you stop doing first?", category: .hypothetical, depth: .deep),
            Question(text: "Would you rather always say what you think or never be misunderstood?", category: .hypothetical, depth: .deep),
            Question(text: "If you could have been born in any era, which would you choose?", category: .hypothetical, depth: .medium),
            Question(text: "If you could send a message to your 16-year-old self, what would it be?", category: .hypothetical, depth: .deep),
            Question(text: "Would you rather have more time or more money — and be honest?", category: .hypothetical, depth: .medium),
            Question(text: "If your house was on fire and everyone was safe, what's the one thing you'd grab?", category: .hypothetical, depth: .medium),
            Question(text: "If you could redesign one aspect of human nature, what would you change?", category: .hypothetical, depth: .deep),
            Question(text: "Would you want to know if your partner was going to leave you before they did?", category: .hypothetical, depth: .deep),
            Question(text: "If you could speak to one person from history for five minutes, who would it be?", category: .hypothetical, depth: .medium),
            Question(text: "If the internet disappeared tomorrow, what would you miss most?", category: .hypothetical, depth: .light),
            Question(text: "Would you rather live a long ordinary life or a short extraordinary one?", category: .hypothetical, depth: .deep),
            Question(text: "If you could bottle one feeling and return to it whenever you wanted, what would it be?", category: .hypothetical, depth: .deep),
            Question(text: "If you had to donate everything you owned except 100 items, what would you keep?", category: .hypothetical, depth: .medium),
            Question(text: "Would you choose to remember every dream you ever have?", category: .hypothetical, depth: .medium),
            Question(text: "If you could ask the universe one question and get an honest answer, what would it be?", category: .hypothetical, depth: .deep),
            Question(text: "If you had to leave your country tomorrow with one bag, where would you go?", category: .hypothetical, depth: .medium),
            Question(text: "Would you rather be deeply understood by one person or liked by everyone?", category: .hypothetical, depth: .deep),
            Question(text: "If you could experience someone else's life for a day, whose would you choose?", category: .hypothetical, depth: .medium),
            Question(text: "If you were told you were living in a simulation, would it change anything for you?", category: .hypothetical, depth: .deep),
            Question(text: "If you could protect someone you love from one hardship, what would it be?", category: .hypothetical, depth: .deep),
            Question(text: "Would you rather always be early or always be fashionably late?", category: .hypothetical, depth: .light),
            Question(text: "If you could wake up tomorrow having forgotten one experience, would you?", category: .hypothetical, depth: .deep),
            Question(text: "If you had to teach the world one thing, what would it be?", category: .hypothetical, depth: .deep),
            Question(text: "Would you rather feel everything deeply or nothing at all?", category: .hypothetical, depth: .deep),
            Question(text: "If you could revisit any moment in your life just to feel it again, which would you pick?", category: .hypothetical, depth: .deep),
            Question(text: "If you woke up tomorrow and everything had worked out, what would your life look like?", category: .hypothetical, depth: .deep),
        ]
    }

    func questions(for category: QuestionCategory) -> [Question] {
        allQuestions.filter { $0.category == category }
    }

    func randomQuestion(for category: QuestionCategory? = nil) -> Question? {
        if let category {
            return questions(for: category).randomElement()
        }
        return allQuestions.randomElement()
    }

    func favoriteQuestions(ids: Set<UUID>) -> [Question] {
        allQuestions.filter { ids.contains($0.id) }
    }

    func shuffledQuestions(for category: QuestionCategory) -> [Question] {
        questions(for: category).shuffled()
    }
}
